"""codeteam.session — Durable Session 持久化与恢复。"""
from codeteam.session.errors import (
    CheckpointMissingError,
    ProviderUnavailableError,
    RepositoryMismatchError,
    SessionAlreadyActiveError,
    SessionAlreadyExistsError,
    SessionCorruptedError,
    SessionError,
    SessionNotFoundError,
    SessionRecoveryRequiredError,
    SessionSchemaUnsupportedError,
    SessionTerminalError,
    WorktreeMissingError,
)
from codeteam.session.models import (
    CURRENT_SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    ActiveOperation,
    ContextMetadata,
    OperationStatus,
    RepositoryRef,
    Session,
    SessionEvent,
    SessionManifest,
    SessionStatus,
    SessionUsage,
    WorktreeRef,
)
from codeteam.session.store import (
    DEFAULT_SESSIONS_DIR_NAME,
    JsonSessionStore,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "DEFAULT_SESSIONS_DIR_NAME",
    "SUPPORTED_SCHEMA_VERSIONS",
    "ActiveOperation",
    "CheckpointMissingError",
    "ContextMetadata",
    "JsonSessionStore",
    "OperationStatus",
    "ProviderUnavailableError",
    "RepositoryMismatchError",
    "RepositoryRef",
    "Session",
    "SessionAlreadyActiveError",
    "SessionAlreadyExistsError",
    "SessionCorruptedError",
    "SessionError",
    "SessionEvent",
    "SessionManifest",
    "SessionNotFoundError",
    "SessionRecoveryRequiredError",
    "SessionSchemaUnsupportedError",
    "SessionStatus",
    "SessionTerminalError",
    "SessionUsage",
    "WorktreeMissingError",
    "WorktreeRef",
]
